### ISSUE TITLE
Icons on Debian Trixie and console

### ISSUE THREAD

**Issue by tukanos** [NotAShelf/microfetch#11]
I'm getting an icon  instead of yours.  Which font do I have to have installed?

![microfetch](https://github.com/user-attachments/assets/6561574b-fbe8-433a-8080-756ccca8e161)

**Comment by NotAShelf** [comment]
You will need a [nerd-fonts](https://github.com/ryanoasis/nerd-fonts) patched font, you can probably find one in your distro's repositories.

**Comment by tukanos** [comment]
I see.  Which one of the nerd-fonts is actually used?  I've tried the symbols only but that does not seem to work.

**Comment by NotAShelf** [comment]
The screenshot should be using Iosevka Mono. I was using a different terminal at the time, and I can't recall setting up a font specifically.

Does your terminal emulator set a font? You will probably need to tell it to use it a nerd-fonts compatible font, or set up fontconfig in your system.

**Comment by tukanos** [comment]
> The screenshot should be using Iosevka Mono. I was using a different terminal at the time, and I can't recall setting up a font specifically.
> 
> Does your terminal emulator set a font? You will probably need to tell it to use it a nerd-fonts compatible font, or set up fontconfig in your system.

That was great comment.  I'm using Console (from The GNOME project), where you need to set he font you want to use and it does not work with other installed.  When I used GNOME terminal on the other hand it worked right away.

Thank you for the hints.
