### ISSUE TITLE
🚨🚨WAY TOO FAST🚨🚨

### ISSUE THREAD

**Issue by deviantsemicolon** [NotAShelf/microfetch#14]
The speed of microfetch, clocking in on my system at around 1 ms to run, makes other programs seem slow by comparison. This may decrease the patience, a valuable commodity in our lives, of many users.

Make microfetch less fast by doing the following:

- Package number display that combs through the entire nix store looking for packages. Maybe even display how many dependencies there are too just to make it slower 
- Display GPU info
- Display local IP
- display time zone using whatever replaces the Geoclue backend that Mozilla had. 
- make the ASCII nix logo an ultra high quality nix logo PNG that the terminal has to render
- Hyper-extensible customization

Failure to do this will result in me being very sad and many people breaking their computers due to impatience :(

**Comment by NotAShelf** [comment]
:trollface:

**Comment by deviantsemicolon** [comment]
:(

**Comment by NotAShelf** [comment]
:)
